# Generated by Django 2.0.8 on 2019-10-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191027_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_hash',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Payment'),
        ),
    ]
