# Generated by Django 2.2.6 on 2019-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191028_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.TextField(default='', max_length=250),
        ),
    ]
